### ISSUE TITLE
Suppress output like crap score?

### ISSUE THREAD

**Issue by ffMathy** [SteveGilham/altcover#106]
Hey Steve.

As you may know, I'm using AltCover as part of the Pruner CLI (https://github.com/pruner/cli). I tell my users to install AltCover to support Pruner, but I'd like a way to not have it output anything at all as part of the test run process.

Currently, it produces output like a "crap" score etc, which I would prefer it not to do.

I haven't been able to find anything about it in the documentation. Is there a way to suppress all this?

**Comment by SteveGilham** [comment]
At the moment, what's on offer is `/p:AltCoverSummaryFormat=B` or  `/p:AltCoverSummaryFormat=R` which replace the OpenCover style summary with a TeamCity ready one.  The problem is the acronym for the change risk anti-patterns score, I presume.

Extending the available options will be easy enough.

**Comment by SteveGilham** [comment]
Should be resolved in release [7.2.800](https://www.nuget.org/packages/AltCover/7.2.800); use `/p:AltCoverSummaryFormat=N` to suppress all summary information

**Comment by ffMathy** [comment]
The proposed solution is great, but I would still argue that AltCover is being too verbose per default. For instance, I still get the list of instrumented assemblies, the "before" and "after" runsettings file paths, and so on.

I would argue that no one would really be interested in these, unless they were trying to figure out if there was a problem with AltCover. Could they be hidden behind a verbose flag? 

The current output actually also creates the need for scrolling up in a "dotnet test" output to see how many tests failed and passed, which is a shame IMO. 

This is a huge improvement though! ❤️🙏

**Comment by SteveGilham** [comment]
Switching off all the informational (and optionally warning) level messages is easy enough, given the way output is handled.  Just pondering the best way to expose the option in the `dotnet test` case.  

ATM, I've got some other plates spinning, so it'll be a couple of days before I rotate back to this.

**Comment by ffMathy** [comment]
That's fine - I'm able to continue with what I've got at the moment.

I'd suggest turning off all kinds of output, unless `/p:AltCoverVerbosity=detailed` is set in `dotnet test` or something similar.

What do you think of that?

**Comment by SteveGilham** [comment]
Messages come in 3 flavours -- informational, warning and error.  If you really want to be able to switch off error messages -- "all kinds of output" -- I can oblige, but it'll be a case of "you asked for it..."

**Comment by ffMathy** [comment]
Yes, but I was thinking that AltCoverVerbosity would then be a "minimum log level".

And then it could default to "Warning", meaning that warnings and higher (errors, fatal, whatever) are included.

But then you can specify "verbose" or "debug" to get lower levels.

**Comment by SteveGilham** [comment]
Should be addressed by release v7.3.802; this controls everything emitted by the AltCover binaries.

**Comment by ffMathy** [comment]
That's perfect, and I love the implementation. How do I specify the verbosity with the `/p:` syntax in `dotnet test`?

**Comment by SteveGilham** [comment]
[As per the docs](https://stevegilham.github.io/altcover/%60dotnet-test%60-integration), like `/p:AltCoverVerbosity="Off”` (or `Warning` or  `Error` if you want to leave some things coming through).

**Comment by ffMathy** [comment]
Ah of course - my bad. Thanks once again! 🙏
